
datadump.location:
    author: C:\Users\15635\Desktop\SpringBoot_REstAPI\Projects\bookSelf\bookself-data-loader\src\main\resources\author_data_dump.txt
    work: C:\Users\15635\Desktop\SpringBoot_REstAPI\Projects\bookSelf\bookself-data-loader\src\main\resources\author_data_dump.txt

spring:
  data:
    cassandra:
        keyspace-name: main
        username: btOtzokZUOZviBBTsrCdQass
        password: 4PF4D33ovOzPrR_JlUF5x_SyHW4ky93OMKfc4bK7HmZ+QUm01YHylhoRC6Ht0ZZwXuEm5RlZXvBQ-I2h99TRfZ1F.CphU6Uvt9W+_K3qnuavxubfNH.WklGqcQpusY_A
        schema-action: recreate
        request:
            timeout: 10s
        connection:
            connect-timeout: 10s
            init-query-timeout: 10s
            
spring.main.allow-circular-references: true

datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: bacd0629-b805-4572-a42c-aade39422efe-1
    region: us-east1	
    keyspace: main
    application.token: AstraCS:btOtzokZUOZviBBTsrCdQass:c8c7aefd0a3d11f7c95cbc9f63ac29529365769c1d715f20abf661345553111c







