spring:
  data:
    cassandra:
        keyspace-name: main
        username: PWZSDRuZezZnblWQLpcufxHU
        password: Qove4,ZRs8Li,Q_zHMUJfCdQ_bcsHvZjhxfLXMWzjX2Sh0SAuoC3BsRBcN.0WTjg7KxwILUExXQekyxZy556XmeeLan3i4U.HlkeFHk3z,0rh+eg1bBaoCqbl0ok9tn5
        schema-action: create-if-not-exists
        request:
            timeout: 10s
        connection:
            connect-timeout: 10s
            init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: sucure-connect.zip

astra.db:
    id: bacd0629-b805-4572-a42c-aade39422efe-1
    region: us-east1	
    keyspace: main
    application.token: AstraCS:PWZSDRuZezZnblWQLpcufxHU:27892019f503fc2f81bf9fe34c6c7099acc24f0e728def104e60dad0311b5d61






